name: Update Dungeon Stats Image

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-node: '3.x'

    - name: Install Dependencies
      run: pip install Pillow requests

    - name: Run Stats Generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python src/update_stats.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "Dungeon-Bot"
        git config --global user.email "bot@github.com"
        git add assets/Statistics_Live.png
        git diff-index --quiet HEAD || git commit -m "Bot: Discovered updated ledger stats"
        git push